#!/bin/sh

#SBATCH --job-name=mbnb_0.10

#SBATCH --output=mbnb.o

#SBATCH --error=mbnb.error

#SBATCH --partition=savio

#SBATCH --time=30:00:00

#SBATCH --nodes=4

#SBATCH --ntasks-per-node=20

#SBATCH --cpus-per-task=1

# QoS:

#SBATCH --qos=nuclear_savio_normal

#

# Account:

#SBATCH -A co_nuclear

#SBATCH --mail-user=keckler@berkeley.edu
#SBATCH --mail-type=all

# run command
mpirun -np 4 --map-by ppr:1:node:pe=20 sss2 -omp 20 mbnb
